[diff_engine]
command='migra --unsafe $1 $2'

[diff_engine.source]
dbname='postgres_vcs_source'
host='localhost'
port=5432
user='postgres'

[diff_engine.target]
dbname='postgres_vcs_target'
host='localhost'
port=5432
user='postgres'

[target]
dbname='postgit_test'
host='localhost'
port=5432
user='postgres'
